services:
  cluster-state:
    image: kubegraph-cluster-state:latest
    container_name: cluster-state-kubegraph
    restart: unless-stopped
    volumes:
      - kubeconfig:/kubeconf
    networks:
      - cluster-state-kubegraph
    environment:
      - CLUSTER_STATE_API_CRED_USER=${CLUSTER_STATE_API_CRED_USER}
      - CLUSTER_STATE_API_CRED_PASSWD=${CLUSTER_STATE_API_CRED_PASSWD}
    depends_on:
      - api

  mongo:
    image: mongo
    container_name: mongo-kubegraph
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27072:27017
    networks:
      - mongo-kubegraph
    volumes:
      - mongo:/data/db

  redis:
    image: redis:8.0.2-alpine3.21
    container_name: redis-kubegraph
    restart: unless-stopped
    networks:
        - redis-kubegraph

  api:
    image: kubegraph-api:latest
    container_name: api-kubegraph
    restart: unless-stopped
    ports:
      - 8888:8000
    networks:
      - mongo-kubegraph
      - api-kubegraph
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - API_AUTH_SECRET_KEY=${API_AUTH_SECRET_KEY}
    depends_on:
      - mongo

  init-db:
    image: kubegraph-init-db:latest
    container_name: init-db-kubegraph
    networks:
      - mongo-kubegraph
    environment:
      - API_AUTH_SECRET_KEY=${API_AUTH_SECRET_KEY}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ADMIN_API_CRED_USER=${ADMIN_API_CRED_USER}
      - ADMIN_API_CRED_PASSWD=${ADMIN_API_CRED_PASSWD}
      - CLUSTER_WATCH_API_CRED_USER=${CLUSTER_WATCH_API_CRED_USER}
      - CLUSTER_WATCH_API_CRED_PASSWD=${CLUSTER_WATCH_API_CRED_PASSWD}
      - CLUSTER_STATE_API_CRED_USER=${CLUSTER_STATE_API_CRED_USER}
      - CLUSTER_STATE_API_CRED_PASSWD=${CLUSTER_STATE_API_CRED_PASSWD}
    depends_on:
      - mongo

  nginx:
    image: nginx:1.27.5-alpine3.21
    container_name: nginx-kubegraph
    networks:
      - api-kubegraph
      - frontend-kubegraph
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8008:80
    depends_on:
      - api

networks:
  cluster-state-kubegraph:
  mongo-kubegraph:
  redis-kubegraph:
  api-kubegraph:
  frontend-kubegraph:

volumes:
  kubeconfig:
    driver: local
  mongo:
    driver: local
